### ISSUE TITLE
Pictures or it didn't happen ;)

### ISSUE THREAD

**Issue by dumblob** [HackerDaGreat57/bpp#6]
The crazier the description the more urgent need to provide screenshots, gifs, videos, pictures, etc. :wink:.

Please add some to document (and perhaps) explain the dev process, your mind flow, and the history of this cool idea!

**Comment by HackerDaGreat57** [comment]
Let me know what you think of the new README.

**Comment by dumblob** [comment]
You mean these changes: https://github.com/HackerDaGreat57/bpp/compare/79c4e795193803ca5f950fede084aa464e7ae2a2...HEAD#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5 ?

For me it is still far from tangible but I will follow your contributions after the month offline and see where this will go :wink:.

Btw. I might have some pointers for you if you would get to a point of feeling it is futile - been there & done that myself.

**Comment by HackerDaGreat57** [comment]
Thanks!

Yeah, I'm really hoping this gets somewhere, unlike my previous attempts at this. :)
